version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: volunteer_db
      POSTGRES_USER: volunteer_user
      POSTGRES_PASSWORD: volunteer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: